# Minimal configuration for running minimal_example.py
# This yaml file can be read

# ---- Signal processing ----
sample_rate: 32000     # 32 kHz (AudioSet / ESC-50)
# FIXME For musical audio analysis, we should probably use different ones..
#    e.g. smaller window size (much fewer mel bins anyways),
#    and more mel bins (e.g. whisper uses 128)
window_size: 1024      # STFT window size
# Can't adapt the STFT hop size to get 1024 frames exactly (instead of 1001) (can't disable the bicubic interpolation)
hop_size: 320          # STFT hop size (orig: 320). 313 gives 1023 frames (not 1024)
mel_bins: 64           # Number of mel bins
fmin: 50               # Min mel frequency
fmax: 14000            # Max mel frequency

clip_samples: 320000  # 10 seconds for 32 kHz

enable_repeat_mode: False # repeat the spectrogram / reshape the spectrogram



# ---- Model hyperparameters ----
classes_num: 527
htsat_spec_size: 256
htsat_patch_size: 4
htsat_stride: [4, 4]
htsat_num_head: [4, 8, 16, 32]
htsat_dim: 96
htsat_depth: [2, 2, 6, 2]
htsat_window_size: 8

# ---- Model options ----
enable_tscam: True  # enable the token-semantic layer
# Some Deprecated Optimization in the model design, check the model code for details
htsat_attn_heatmap: False
htsat_hier_output: False
htsat_use_max: False

# ---- Training options ----
training_spec_augmentation: False
loss_type: "clip_bce" #   AudioSet & SCV2: "clip_bce" |  ESC-50: "clip_ce"

