# Minimal configuration for running minimal_example.py
# This yaml file can be read

# ---- Signal processing ----
# Compared to default config: 16kHz, smaller window, more mel bins are less time frames (bigger hop relative to sr)
sample_rate: 16000
window_size: 512       # STFT window size
# Adapted STFT hop size to get 512 frames exactly (instead of 501), to disable the bicubic interpolation
hop_size: 313          # STFT hop size (orig: 320)
mel_bins: 128           # Number of mel bins
fmin: 50               # Min mel frequency
fmax: 8000            # Max mel frequency

clip_samples: 160000

enable_repeat_mode: False # repeat the spectrogram / reshape the spectrogram



# ---- Model hyperparameters ----
classes_num: 527
htsat_spec_size: 256
htsat_patch_size: 4
htsat_stride: [4, 4]
htsat_num_head: [4, 8, 16, 32]
htsat_dim: 96
htsat_depth: [2, 2, 6, 2]
htsat_window_size: 8

# ---- Model options ----
enable_tscam: True  # enable the token-semantic layer
# Some Deprecated Optimization in the model design, check the model code for details
htsat_attn_heatmap: False
htsat_hier_output: False
htsat_use_max: False

# ---- Training options ----
training_spec_augmentation: False
loss_type: "clip_bce" #   AudioSet & SCV2: "clip_bce" |  ESC-50: "clip_ce"

